#!/bin/bash 
### Begin BSUB Options 
#BSUB -P GEO132 
#BSUB -J kokkos_cuda_smt4
#BSUB -W 2:00 
#BSUB -nnodes 1 
#BSUB -o cuda_output.log
#BSUB -e cuda_error.log
### End BSUB Options and begin shell commands

cd /gpfs/alpine/proj-shared/geo132/module_build/elm_kernels/
module use modulefiles/
module load elm_kernels/scalability/kokkos/cuda
module load gcc/7.4.0
module load cuda
module load parallel-netcdf

export CUDA_LAUNCH_BLOCKING=1
export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1

cd /gpfs/alpine/proj-shared/geo132/module_build/elm_kernels/repos/scalability/tests/tests_kokkos_c
make

for i in 1 2 3 6
do
        jsrun -n $i -a 1 -c 1 -g 1 -r $i -l GPU-CPU -d packed -b packed:1 ./test_CanopyHydrology_module.cuda >> cudasmt4.log
done
