#!/bin/bash 
### Begin BSUB Options 
#BSUB -P GEO132 
#BSUB -J kokkos_openmp_smt1node1
#BSUB -W 2:00 
#BSUB -nnodes 1 
#BSUB -alloc_flags "smt1"
#BSUB -o kokkos_openmp_smt1node1_output.log
#BSUB -e kokkos_openmp_smt1node1_error.log
### End BSUB Options and begin shell commands

cd /gpfs/alpine/proj-shared/geo132/module_build/elm_kernels
module use modulefiles/
module load elm_kernels/scalability/kokkos/openmp
module load gcc/7.4.0
module load cuda
module load parallel-netcdf
export CUDA_LAUNCH_BLOCKING=1
export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1

cd /gpfs/alpine/proj-shared/geo132/module_build/elm_kernels/repos/scalability/tests/tests_kokkos_c
make clean

make

for i in 1 2 4 16
do
        export OMP_NUM_THREADS=$i
        jsrun -n $i -c $i -r $i -p 1 -l CPU-CPU -d packed -b rs ./test_CanopyHydrology_module.host >> openmpsmt1.log
done
