#!/bin/bash 
### Begin BSUB Options 
#BSUB -P GEO132 
#BSUB -J kokkos_openmp_smt4node1
#BSUB -W 2:00 
#BSUB -nnodes 1 
#BSUB -alloc_flags "smt4"
#BSUB -o kokkos_openmp_smt4node1_output.log
#BSUB -e kokkos_openmp_smt4node1_error.log
### End BSUB Options and begin shell commands

cd /gpfs/alpine/proj-shared/geo132/ELM/env/elm_kernels_env
module use modulefiles/
module load elm_kernels/scalability/kokkos/openmp
module load gcc/7.4.0
module load parallel-netcdf

cd /gpfs/alpine/proj-shared/geo132/ELM/repo/utils/tests/tests_kokkos_c
#make clean
#make
#cp test_CanopyHydrology_module.host exeopenmp
for i in 1 2 4 8 16 32
do
        num_threads=$((4*i))
        export OMP_NUM_THREADS=$num_threads
        jsrun -n 1 -a 1 -c $i -r 1 -l CPU-CPU -d packed -b rs ./exeopenmp >> openmpsmt4.results
done
rm exeopenmp
