SRCDIR	      =	../../src/
OBJECT        = ../../src/

default: links

include $(OBJECT)config/Makefile.config

OBJS= forcing1.nc forcing2.nc forcing3.nc forcing4.nc forcing5.nc \
      forcing6.nc forcing7.nc forcing8.nc forcing9.nc forcing10.nc \
      forcing11.nc forcing12.nc forcing13.nc forcing14.nc forcing15.nc \
      forcing16.nc forcing17.nc forcing18.nc forcing19.nc forcing20.nc \
      forcing21.nc forcing22.nc forcing23.nc forcing24.nc \
      surfacedataBRW.nc surfacedataWBW.nc



links: $(OBJS)

forcing1.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_wbw/CLM1PT_data/2003-01.nc forcing1.nc

forcing10.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_wbw/CLM1PT_data/2003-10.nc forcing10.nc

forcing11.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_wbw/CLM1PT_data/2003-11.nc forcing11.nc

forcing12.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_wbw/CLM1PT_data/2003-12.nc forcing12.nc

forcing13.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_US-Brw/CLM1PT_data/2003-01.nc forcing13.nc

forcing14.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_US-Brw/CLM1PT_data/2003-02.nc forcing14.nc

forcing15.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_US-Brw/CLM1PT_data/2003-03.nc forcing15.nc

forcing16.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_US-Brw/CLM1PT_data/2003-04.nc forcing16.nc

forcing17.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_US-Brw/CLM1PT_data/2003-05.nc forcing17.nc

forcing18.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_US-Brw/CLM1PT_data/2003-06.nc forcing18.nc

forcing19.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_US-Brw/CLM1PT_data/2003-07.nc forcing19.nc

forcing2.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_wbw/CLM1PT_data/2003-02.nc forcing2.nc

forcing20.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_US-Brw/CLM1PT_data/2003-08.nc forcing20.nc

forcing21.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_US-Brw/CLM1PT_data/2003-09.nc forcing21.nc

forcing22.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_US-Brw/CLM1PT_data/2003-10.nc forcing22.nc

forcing23.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_US-Brw/CLM1PT_data/2003-11.nc forcing23.nc

forcing24.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_US-Brw/CLM1PT_data/2003-12.nc forcing24.nc

forcing3.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_wbw/CLM1PT_data/2003-03.nc forcing3.nc

forcing4.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_wbw/CLM1PT_data/2003-04.nc forcing4.nc

forcing5.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_wbw/CLM1PT_data/2003-05.nc forcing5.nc

forcing6.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_wbw/CLM1PT_data/2003-06.nc forcing6.nc

forcing7.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_wbw/CLM1PT_data/2003-07.nc forcing7.nc

forcing8.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_wbw/CLM1PT_data/2003-08.nc forcing8.nc

forcing9.nc:
	ln -s $(ELM_DATA_LOCATION)/atm/datm7/1x1pt_wbw/CLM1PT_data/2003-09.nc forcing9.nc

surfacedataBRW.nc:
	ln -s $(ELM_DATA_LOCATION)/lnd/clm2/surfdata_map/surfdata_1x1pt_US-Brw_simyr1850.nc surfacedataBRW.nc

surfacedataWBW.nc:
	ln -s $(ELM_DATA_LOCATION)/lnd/clm2/surfdata_map/surfdata_1x1pt_wbw_simyr1850.nc surfacedataWBW.nc
