# Available from: git clone https://code.ornl.gov/isp/acme_inputdata
ELM_DATA_LOCATION = /home/7hp/Downloads/acme_inputdata

# assumes you have a working NETCDF.  This can easily be the version built by
# ATS as a part of an ATS installation.
NETCDF_ROOT                     = ${AMANZI_TPLS_DIR}

# assumes you have a working fortran and c++ compilers with libraries
FC            = gfortran
FC_FLAGS       = -fimplicit-none -free -g3 -fbounds-check -fbacktrace
FC_LIB_ROOT = /usr/lib/gcc/x86_64-linux-gnu/8

CC	      = g++
CPP_FLAGS      = -g -Wall -Wshadow -std=c++11
STD_LIB_ROOT  = /usr

NVCC=nvcc
CUDA_FLAGS= -std=c++11 -c -arch=sm_60
CUDA_LIBS= -lopenblas -lpthread -lcudart -lcublas
CUDA_LIBDIRS=-L/usr/local/cuda-10.0/lib64
CUDA_INCDIRS=-I/usr/local/cuda-10.0/include

# note, the linker should almost always be your fortran compiler, NOT your c compiler
#LINKER        = gfortran
CC_LD_FLAGS      = -L$(SRCDIR) -lelm -L$(NETCDF_ROOT)/lib -lnetcdf -L$(STD_LIB_ROOT)/lib -lstdc++ #-L$(FC_LIB_ROOT) -lgfortran
FC_LD_FLAGS      = -L$(SRCDIR) -lelm -L$(NETCDF_ROOT)/lib -lnetcdff
CUDA_LD_FLAGS    = -L$(SRCDIR) -lelm -L$(NETCDF_ROOT)/lib -lnetcdf -L$(CUDA_LIBDIRS) -lstdc++ -lopenblas -lpthread -lcudart -lcublas

# ------------------------------------------------
# Hopefully below shouldn't have to be changed.
# ------------------------------------------------

.PHONY: all

.PRECIOUS: %.cc.o %.F90.o %.cpp.o %.cu.o
.SUFFIXES: .cc.o .F90.o .cpp.o .cu.o .cc .F90 .cpp .cu

%.F90.o: %.F90
	$(FC) $(FC_FLAGS) -c $< -o $@ 
%.cc.o: %.cc
	$(CXX) $(CC_FLAGS) $(CPP_FLAGS) $(INC_FLAGS) -c $< -o $@
%.cpp.o: %.cpp
	$(CXX) $(CC_FLAGS) $(CPP_FLAGS) $(INC_FLAGS) -c $< -o $@
%.cu.o: %.cu
	$(NVCC) $(CUDA_FLAGS) $(INC_FLAGS) -c $< -o $@

SHELL         = /bin/sh



ELM_LIB				= libelm.a
ELM_LIBS                        = -lelm
ELM_DIR                         = elm


ELM_UTILS_DIR = cime_utils

LIB_SUFFIX=.a

M4	      =	
RM            = rm -fr
CP            = cp
XARGS	      = 
AR	      = ar

######################################################################
# Rules used in all directories.
######################################################################

ELM_CLEAN=$(RM) -f *.o *.ii *.int.c *.log *.log.* stamp-* core core.* stats -r ti_files ii_files *.mod *.a



