# compile flags
FCFLAGS += $(NETCDF_INC_FLAGS) $(ELM_INC_FLAGS)
CXX_FLAGS += $(NETCDF_INC_FLAGS) $(ELM_INC_FLAGS)
INC_FLAGS += $(NETCDF_INC_FLAGS) -I$(ELM_ROOT) 

# linking flags
CXX_LD_FLAGS += $(NETCDF_FLAGS)# -L$(STD_LIB_ROOT)/lib -lstdc++
CUDA_LD_FLAGS = $(NETCDF_FLAGS)# -L$(CUDA_LIBDIRS) -lstdc++ -lpthread -lcudart -lcublas

#
# rules
#
.PHONY: all
.PRECIOUS: %.cc.o %.F90.o %.cpp.o %.cu.o
.SUFFIXES: .cc.o .F90.o .cpp.o .cu.o .cc .F90 .cpp .cu

%.F90.o: %.F90
	$(FC) $(FC_FLAGS) -c $< -o $@ 
%.cc.o: %.cc
	$(CXX) $(CXXFLAGS) ${KOKKOS_CXXFLAGS} $(INC_FLAGS) -DATM_DATA_LOCATION=$(ATM_DATA_LOCATION) -DELM_DATA_LOCATION=$(ELM_DATA_LOCATION) -c $< -o $@
%.cu.o: %.cu
	$(NVCC) $(CUDA_FLAGS) -I$(MPI_LIB_ROOT)/include $(INC_FLAGS) -c $< -o $@



SHELL         = /bin/sh

LIB_SUFFIX=.a

M4	      =	
RM            = rm -fr
CP            = cp
XARGS	      = 
AR	      = ar

######################################################################
# Rules used in all directories.
######################################################################

ELM_CLEAN=$(RM) -f *.o *.ii *.int.c *.log *.log.* stamp-* core core.* stats -r ti_files ii_files *.mod *.a

