ifdef HAVE_MPI

# turn on MPI, PNETCDF
CXX = $(MPICXX)
CXXFLAGS += -DHAVE_MPI
FC = mpifort

endif

ifdef HAVE_PNETCDF

INC_FLAGS += $(PNETCDF_INC_FLAGS)
CXX_LD_FLAGS += $(PNETCDF_FLAGS)
CUDA_LD_FLAGS = $(PNETCDF_FLAGS)
CXXFLAGS += -DHAVE_PNETCDF

else

# use NETCDF
INC_FLAGS += $(NETCDF_INC_FLAGS)
CXX_LD_FLAGS += $(NETCDF_FLAGS)
CUDA_LD_FLAGS = $(NETCDF_FLAGS)

endif


# compile flags
CXXFLAGS += -DATM_DATA_LOCATION=$(ATM_DATA_LOCATION) -DELM_DATA_LOCATION=$(ELM_DATA_LOCATION)

INC_FLAGS +=  -I$(ELM_ROOT) 

#
# rules
#
.PHONY: all
.PRECIOUS: %.cc.o %.F90.o %.cpp.o %.cu.o
.SUFFIXES: .cc.o .F90.o .cpp.o .cu.o .cc .F90 .cpp .cu

%.F90.o: %.F90
	$(FC) $(FC_FLAGS) -c $< -o $@ 
%.cc.o: %.cc
	$(CXX) $(CXXFLAGS) ${KOKKOS_CXXFLAGS} $(INC_FLAGS) -c $< -o $@
%.cu.o: %.cu
	$(NVCC) $(CUDA_FLAGS) -I$(MPI_LIB_ROOT)/include $(INC_FLAGS) -c $< -o $@



SHELL         = /bin/sh

LIB_SUFFIX=.a

M4	      =	
RM            = rm -fr
CP            = cp
XARGS	      = 
AR	      = ar

######################################################################
# Rules used in all directories.
######################################################################

ELM_CLEAN=$(RM) -f *.o *.ii *.int.c *.log *.log.* stamp-* core core.* stats -r ti_files ii_files *.mod *.a

