# compile flags
FCFLAGS += $(NETCDF_INC_FLAGS) $(ELM_INC_FLAGS)
CXXFLAGS += $(NETCDF_INC_FLAGS) $(ELM_INC_FLAGS)

# linking flags
CC_LD_FLAGS += $(NETCDF_FLAGS) -L$(STD_LIB_ROOT)/lib -lstdc++ -L$(FC_LIB_ROOT) -lgfortran
#CC_LD_FLAGS += $(NETCDF_FLAGS) -L$(STD_LIB_ROOT)/lib -lstdc++ -L$(MPI_LIB_ROOT)/lib -L$(FC_LIB_ROOT) -lgfortran
FC_LD_FLAGS +=  $(NETCDF_FLAGS)f
CXX_LD_FLAGS +=  $(NETCDF_FLAGS)
#CXX_LD_FLAGS +=  $(NETCDF_FLAGS) -I$(MPI_LIB_ROOT)/include -L$(MPI_LIB_ROOT)/lib -lmpi
CUDA_LD_FLAGS = $(NETCDF_FLAGS) -L$(CUDA_LIBDIRS) -lstdc++ -lpthread -lcudart -lcublas

#
# rules
#
.PHONY: all
.PRECIOUS: %.cc.o %.F90.o %.cpp.o %.cu.o
.SUFFIXES: .cc.o .F90.o .cpp.o .cu.o .cc .F90 .cpp .cu

%.F90.o: %.F90
	$(FC) $(FC_FLAGS) -c $< -o $@ 
%.cc.o: %.cc
	$(CC) $(CXXFLAGS) $(INC_FLAGS) -c $< -o $@
%.cpp.o: %.cpp
	$(CXX) $(CXXFLAGS) $(KOKKOS_CXXFLAGS) $(NETCDF_INC_FLAGS) $(ELM_INC_FLAGS) -c $< -o $@ #-I$(MPI_LIB_ROOT)/include
%.cu.o: %.cu
	$(NVCC) $(CUDA_FLAGS) -I$(MPI_LIB_ROOT)/include $(INC_FLAGS) -c $< -o $@



SHELL         = /bin/sh

LIB_SUFFIX=.a

M4	      =	
RM            = rm -fr
CP            = cp
XARGS	      = 
AR	      = ar

######################################################################
# Rules used in all directories.
######################################################################

ELM_CLEAN=$(RM) -f *.o *.ii *.int.c *.log *.log.* stamp-* core core.* stats -r ti_files ii_files *.mod *.a

